name: Start Tests
on:
  push:
    branches:
      - test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Tests
        run: |
          dotnet test --collect:"XPlat Code Coverage"