name: Start Tests
on:
  push:
    branches:
      - test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.COVER_TOKEN }} # not required for public repos
          files: ./Calculator.Test/TestResults/../coverage.opencover.xml
          flags: unittests 
          name: codecov-umbrella
          fail_ci_if_error: true 
          verbose: true
